default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: jazzok_development

test:
  <<: *default
  database: jazzok_test

production:
  <<: *default
  database: jazzok_production
  username: jazzok
  password: <%= ENV['JAZZOK_DATABASE_PASSWORD'] %>
